name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script (builds Docker image)
        run: ./build.sh build-only

      - name: Tag Docker image with latest and commit SHA
        run: |
          # The build.sh creates docker.io/cniweb/xmrig:6.22.2
          # We need to tag it for latest and commit SHA across all registries
          
          # Tag for Docker Hub
          docker tag docker.io/cniweb/xmrig:6.22.2 docker.io/cniweb/xmrig:latest
          docker tag docker.io/cniweb/xmrig:6.22.2 docker.io/cniweb/xmrig:${{ github.sha }}
          
          # Tag for GitHub Container Registry
          docker tag docker.io/cniweb/xmrig:6.22.2 ghcr.io/cniweb/xmrig:latest
          docker tag docker.io/cniweb/xmrig:6.22.2 ghcr.io/cniweb/xmrig:${{ github.sha }}
          
          # Tag for Quay.io
          docker tag docker.io/cniweb/xmrig:6.22.2 quay.io/cniweb/xmrig:latest
          docker tag docker.io/cniweb/xmrig:6.22.2 quay.io/cniweb/xmrig:${{ github.sha }}

      - name: Push Docker images to all registries
        run: |
          # Push to Docker Hub
          docker push docker.io/cniweb/xmrig:latest
          docker push docker.io/cniweb/xmrig:${{ github.sha }}
          
          # Push to GitHub Container Registry
          docker push ghcr.io/cniweb/xmrig:latest
          docker push ghcr.io/cniweb/xmrig:${{ github.sha }}
          
          # Push to Quay.io
          docker push quay.io/cniweb/xmrig:latest
          docker push quay.io/cniweb/xmrig:${{ github.sha }}